services:
  iombian-shutdown-handler:
    image: iombian-shutdown-handler
    container_name: iombian-shutdown-handler
    privileged: true
    restart: unless-stopped
    volumes:
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /bin/systemctl:/bin/systemctl
    environment:
      SHUTDOWN_EVENT: ${SHUTDOWN_EVENT:-long_click}
      LOG_LEVEL: ${LOG_LEVEL:-INFO} 
    networks:
      - iombian-internal-services 
networks:
  iombian-internal-services:
    external: true
